### ISSUE TITLE
[CONNECT] No LiveID discovered until now

### ISSUE THREAD

**Issue by Jastroger** [foxriver76/ioBroker.xbox#5]
Hi foxriver,

tried out your xbox adapter this week - works great!
I've one question about a log warning I get: "[CONNECT] No LiveID discovered until now"

This is after I shut my XBox down. It does not appear when the box is alive.
I entered my LiveID in the settings. Works fine - maybe I misunderstood something?

Installed version is 0.4.4

best regards,
Jan

**Comment by foxriver76** [comment]
Thanks four your feedback. 
The message is maybe a bit misleading, because it is a bit legacy of older versions and a bit unspecific. 
The logging should only happen once per started instance and happens when the Xbox (IP address given in the config) is responds to a ping probe, but the provided live id is not answering on discover packages. Summary: Sometimes the Xbox responds to a ping when it is offline, then the adapter sends a discovery package and Xbox isn't responding and Xbox has not been discovered before in the running process --> Message will be logged.
