### ISSUE TITLE
XBox live auth not working on raspberry

### ISSUE THREAD

**Issue by L-C-P** [foxriver76/ioBroker.xbox#61]
Hi,

I could not log into my live account from a raspberry. If logged into my raspberry from my web browser on http://raspberrypi. If I click the "Authentication inactive, activate here!" link, I can grant access to the node server on xbox live. But as long as "localhost" is configured for the oauth return, it's not working. I can not change the return url, as long as it is configured in your app settings on live, because of security reasons. Can you maybe add a second auth url, like localhostdummy? Because then i can set localhostdummy in my hosts file and set it also to the raspberry.

**Comment by foxriver76** [comment]
If you speak german, long story short, [take a look here.](https://forum.iobroker.net/topic/37077/xbox-adapter-fehler-pi4/29)

Otherwise, the steps to authenticate again:
 -   Wait until the logging for Rest-Server appears started, then click on the link in the log or click on the link in the adapter settings.
-    Here you will either be prompted to log in, or you were automatically logged in to MS
-    Then an error should appear that the page is not available, the link should start with localhost
-    Copy the link, go to the terminal, and curl "<insert link>".
-    Now you should see in the log that you are authenticated
-    After restarting the server you are unfortunately logged out again, **I'm still waiting for feedback of the dependency developers that this will all be more user-friendly again.**

**Comment by Ajimaru** [comment]
That helped, thank you.
